project_id = "hcpfjhcfhfjqusbjnkfa"

[functions.chat]
verify_jwt = false

[functions.search-part-image]
verify_jwt = false

[functions.save-image-from-url]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.notify-admin-new-application]
verify_jwt = false

[functions.notify-catalog-new]
verify_jwt = false

[functions.reset-password-by-phone]
verify_jwt = false

[functions.send-dealer-notification]
verify_jwt = false

[functions.send-push]
verify_jwt = false

[functions.verify-product-images]
verify_jwt = false

[functions.parse-price-list-pdf]
verify_jwt = false

[functions.create-paymob-intention]
verify_jwt = false

[functions.paymob-webhook]
verify_jwt = false